ボウリングスコア計算プログラム提出用
ryotori1024/ruby-practices pull request #3
Opened 2021-02-09 14:25 UTC by ryotori1024

ボウリングスコア計算プログラム提出用として作成しました。
レビューをお願いいたします。

2021-02-13 13:34 UTC, kakutani requested changes
まず、気になったところをコメントします。

それぞれの分岐のところで、何をしようとしているのかをコードコメントで補っているのは、
読み進めていくうえでわかりやすかったです。

一方、読んでいくうえで特に情報が増えていないコードコメントもあるので、
それは削ってもいいかもしれません(総合得点を出力、とかは見ればわかる)。

2021-02-13 13:34 UTC, kakutani commented on 04.bowling/bowling.rb
> +scores.each do |score_temp|
ブロックパラメータなので、`score_temp`の`_temp`は不要だと思います。
(`scores`に格納されているひとつひとうのデータは`score`だと思います)

2021-02-13 13:34 UTC, kakutani commented on 04.bowling/bowling.rb
> +frame_count = 0
「`frame_count` は1〜10なんだ」という考えであれば、ここは1から始めても構わないと思います。if文で都度`frame_count + 1`していることのほうに違和感を覚えました。

2021-02-13 13:34 UTC, kakutani commented on 04.bowling/bowling.rb
> +frames.each do |frame_tmp|
```suggestion
frames.each do |frame|
```

2021-02-13 13:34 UTC, kakutani commented on 04.bowling/bowling.rb
>  frames_index = 0
`frames#each`するときに、インデックス付きで呼び出せば、このローカル変数は不要かもしれません。`each_with_index`を調べてみてください。

2021-02-13 13:34 UTC, kakutani commented on 04.bowling/bowling.rb
>  p point
```suggestion
puts point
```

`p`は「主にデバッグ用」です。
https://rurema.clear-code.com/3.0.0/method/Kernel/m/p.html

2021-02-15 13:15 UTC, ryotori1024 commented
@kakutani様
再度アップし直しました。
再レビューをお願いします。

2021-02-15 23:55 UTC, kakutani reviewed
変数の名前について、コメントしました。

2021-02-15 23:55 UTC, kakutani commented on 04.bowling/bowling.rb
> +frame_temp = []
`frame_temp` の `_temp` は使い方であって中身の説明になっていません。
「一時的に使う」のはあらゆるローカル変数が一時的な存在なので、読み手に対して情報が増えていません。
これが特別に「一時的」である理由が読み取れませんでした。

`frames`の配列の要素なのであれば `frame` でよさそうです。

2021-02-15 23:55 UTC, kakutani commented on 04.bowling/bowling.rb
> +frames.each_with_index do |frame, frames_index|
ここではブロックパラメータは`frames`のインデックスであることは自明なので、`i` といった短い、慣習的に使われている名前を使ってもらって構わないです。
(変数名の長さに対して、読み手への情報はさほど増えていない)

2021-02-18 13:05 UTC, ryotori1024 commented
@kakutani様
何度も申し訳ありません。
再レビューをお願いいたします。

2021-02-18 13:13 UTC, kakutani commented
お詫びにはおよびません。こちらこそ、対応おつかれさまです 🍵

2021-02-18 13:14 UTC, kakutani approved these changes
レビューOKです。

2021-02-18 13:30 UTC, ryotori1024 commented
ありがとうございます！

2021-03-11 13:25 UTC, merged